name: Debricked SCA scan

on: workflow_dispatch

jobs:
  debricked-sca-scan:
    runs-on: ubuntu-latest
    name: Debricked SCA CLI
    steps:
      - uses: actions/checkout@v3
      - uses: debricked/actions@v3
     # - uses: debricked/actions/scan-non-docker@v3  #NON docker actions
     # - uses: debricked/actions/resolve@v3
     # - uses: debricked/actions/resolve-non-docker@v3  #NON docker actions
        env:
          DEBRICKED_TOKEN: ${{ secrets.DEBRICKED_TOKEN }}

    debricked-sca-scan-CLI:
    runs-on: ubuntu-latest
    name: Debricked SCA CLI
    needs: debricked-sca-scan
    steps:
      - uses: actions/checkout@v3
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Debricked scan
        run: |
          curl -L https://github.com/debricked/cli/releases/latest/download/cli_linux_x86_64.tar.gz | tar -xz debricked
          ./debricked scan . --access-token "8e91c5d87506cf1246061015df3aac7685532459ec8ab6e9"