name: Nuclei DAST scan
on: workflow_dispatch
permissions:
  contents: read
  packages: read
  issues: write
  
jobs:
  nuclei-dast-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Nuclei DAST Scan
        uses: projectdiscovery/nuclei-action@main
        with:
          target: https://ginandjuice.shop/
          #urls: urls.txt
          flags: "-severity critical,high,medium,low -stats"
          github-report: true
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: GitHub Workflow artifacts
        uses: actions/upload-artifact@v3
        with:
          name: nuclei.log
          path: nuclei.log

