name: Snyk sca scan
on: workflow_dispatch

jobs:
  snyk-sca-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: snyk/actions/setup@master
      - uses: actions/setup-go@v1
        continue-on-error: true
        with:
          go-version: '1.13'
      - name: Snyk monitor
        continue-on-error: true
        run: |
          pip install -r requirements.txt
          snyk test --all-projects
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
