name: ZAP DAST scan
on: workflow_dispatch

jobs:
  zap-dast-scan:
    runs-on: ubuntu-latest
    name: ZAP DAST scan
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.6.1
        with:
          docker_name: 'owasp/zap2docker-stable'
          target: 'https://ginandjuice.shop'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'
